-- --------------------------------------------------
-- Dropping existing mock data
-- --------------------------------------------------
DELETE FROM [dbo].[USERADDRESS]
DELETE FROM [dbo].[ADDRESSES]
DELETE FROM [dbo].[USERS]

GO

-- --------------------------------------------------
-- Creating mock data
-- --------------------------------------------------

-- Creating user data
insert into users (FirstName, LastName, Email, Phone) values ('John', 'Hicks', 'Skyvu', '(402) 129-8483')
insert into users (FirstName, LastName, Email, Phone) values ('Nicole', 'Ford', 'Jaloo', '(551) 261-1937')
insert into users (FirstName, LastName, Email, Phone) values ('Helen', 'Parker', 'Wikibox', '(739) 864-9151')
insert into users (FirstName, LastName, Email, Phone) values ('George', 'George', 'Meezzy', '(554) 350-6881')
insert into users (FirstName, LastName, Email, Phone) values ('Dennis', 'Clark', 'Buzzshare', '(672) 378-2461')
insert into users (FirstName, LastName, Email, Phone) values ('Douglas', 'Day', 'Teklist', '(703) 342-5520')
insert into users (FirstName, LastName, Email, Phone) values ('Phyllis', 'Gordon', 'Browseblab', '(606) 264-2629')
insert into users (FirstName, LastName, Email, Phone) values ('Michael', 'Lee', 'Jaxworks', '(985) 163-3510')
insert into users (FirstName, LastName, Email, Phone) values ('Martha', 'Turner', 'Babbleblab', '(595) 367-6416')
insert into users (FirstName, LastName, Email, Phone) values ('Walter', 'Wells', 'Rhybox', '(632) 550-5262')
insert into users (FirstName, LastName, Email, Phone) values ('Ann', 'Harrison', 'Wikido', '(780) 376-8277')
insert into users (FirstName, LastName, Email, Phone) values ('Peter', 'Rice', 'Lazz', '(565) 589-1993')
insert into users (FirstName, LastName, Email, Phone) values ('Kevin', 'Franklin', 'Realfire', '(221) 205-8526')
insert into users (FirstName, LastName, Email, Phone) values ('James', 'Carroll', 'Realbuzz', '(890) 904-9774')
insert into users (FirstName, LastName, Email, Phone) values ('Virginia', 'Matthews', 'Minyx', '(112) 764-3227')
insert into users (FirstName, LastName, Email, Phone) values ('Sarah', 'Hayes', 'Flashspan', '(240) 398-9783')
insert into users (FirstName, LastName, Email, Phone) values ('Jesse', 'Perry', 'Oyoloo', '(247) 927-1290')
insert into users (FirstName, LastName, Email, Phone) values ('Nicholas', 'Crawford', 'Yamia', '(250) 581-4508')
insert into users (FirstName, LastName, Email, Phone) values ('Janice', 'Russell', 'Bluezoom', '(838) 835-3504')
insert into users (FirstName, LastName, Email, Phone) values ('Mildred', 'Brooks', 'Devcast', '(739) 273-7799')
insert into users (FirstName, LastName, Email, Phone) values ('Gerald', 'Scott', 'Rhynoodle', '(857) 133-2211')
insert into users (FirstName, LastName, Email, Phone) values ('Jacqueline', 'Alexander', 'Yotz', '(969) 849-5837')
insert into users (FirstName, LastName, Email, Phone) values ('Shawn', 'Lane', 'Devpoint', '(266) 700-5645')
insert into users (FirstName, LastName, Email, Phone) values ('Judith', 'Fox', 'Jetwire', '(439) 689-9214')
insert into users (FirstName, LastName, Email, Phone) values ('Beverly', 'Butler', 'Babbleset', '(296) 212-7822')
insert into users (FirstName, LastName, Email, Phone) values ('Roy', 'Myers', 'Skyndu', '(640) 949-7401')
insert into users (FirstName, LastName, Email, Phone) values ('Andrew', 'Spencer', 'Pixope', '(867) 256-1080')
insert into users (FirstName, LastName, Email, Phone) values ('Antonio', 'Olson', 'Demimbu', '(492) 384-5387')
insert into users (FirstName, LastName, Email, Phone) values ('Marilyn', 'Fowler', 'Flashpoint', '(782) 340-2163')
insert into users (FirstName, LastName, Email, Phone) values ('Alan', 'Nelson', 'Innojam', '(342) 191-9719')
insert into users (FirstName, LastName, Email, Phone) values ('Timothy', 'Henderson', 'Eidel', '(750) 693-4467')
insert into users (FirstName, LastName, Email, Phone) values ('Ernest', 'Roberts', 'Rooxo', '(265) 943-2056')
insert into users (FirstName, LastName, Email, Phone) values ('Howard', 'Williamson', 'Mynte', '(514) 296-3348')
insert into users (FirstName, LastName, Email, Phone) values ('Bruce', 'Boyd', 'Oyonder', '(403) 862-3985')
insert into users (FirstName, LastName, Email, Phone) values ('Tina', 'Williams', 'Realbridge', '(438) 635-8138')
insert into users (FirstName, LastName, Email, Phone) values ('Wayne', 'Griffin', 'Aimbo', '(600) 306-6793')
insert into users (FirstName, LastName, Email, Phone) values ('Alice', 'Hunter', 'Ntags', '(583) 303-8374')
insert into users (FirstName, LastName, Email, Phone) values ('Judy', 'Flores', 'Skiptube', '(145) 616-3660')
insert into users (FirstName, LastName, Email, Phone) values ('Matthew', 'Moreno', 'Skaboo', '(981) 823-3298')
insert into users (FirstName, LastName, Email, Phone) values ('Todd', 'Chapman', 'Innotype', '(134) 498-5039')
insert into users (FirstName, LastName, Email, Phone) values ('Jimmy', 'Reynolds', 'Youfeed', '(122) 186-7549')
insert into users (FirstName, LastName, Email, Phone) values ('Joan', 'Grant', 'Leexo', '(494) 923-4825')
insert into users (FirstName, LastName, Email, Phone) values ('Harold', 'Fernandez', 'Bubblebox', '(827) 371-9275')
insert into users (FirstName, LastName, Email, Phone) values ('Heather', 'Gray', 'Eabox', '(950) 393-2322')
insert into users (FirstName, LastName, Email, Phone) values ('Fred', 'Black', 'Snaptags', '(930) 670-9200')
insert into users (FirstName, LastName, Email, Phone) values ('Steven', 'Lynch', 'Edgewire', '(609) 715-4859')
insert into users (FirstName, LastName, Email, Phone) values ('Johnny', 'Rodriguez', 'Yakijo', '(795) 591-5681')
insert into users (FirstName, LastName, Email, Phone) values ('Kimberly', 'Ramos', 'Photospace', '(111) 124-1272')
insert into users (FirstName, LastName, Email, Phone) values ('Kathy', 'Morales', 'Yacero', '(439) 507-4686')
insert into users (FirstName, LastName, Email, Phone) values ('Rachel', 'Watson', 'Jabbercube', '(958) 755-8967')
insert into users (FirstName, LastName, Email, Phone) values ('Christopher', 'Ortiz', 'Kwinu', '(715) 760-4852')
insert into users (FirstName, LastName, Email, Phone) values ('Susan', 'Adams', 'Skilith', '(803) 872-7435')
insert into users (FirstName, LastName, Email, Phone) values ('Gregory', 'Larson', 'Agivu', '(613) 438-2983')
insert into users (FirstName, LastName, Email, Phone) values ('Samuel', 'Warren', 'JumpXS', '(969) 159-7815')
insert into users (FirstName, LastName, Email, Phone) values ('Joshua', 'Gibson', 'Tavu', '(932) 413-9951')
insert into users (FirstName, LastName, Email, Phone) values ('Katherine', 'Simpson', 'Edgetag', '(348) 634-1216')
insert into users (FirstName, LastName, Email, Phone) values ('Chris', 'Ross', 'Chatterbridge', '(383) 272-1403')
insert into users (FirstName, LastName, Email, Phone) values ('Philip', 'Gilbert', 'InnoZ', '(712) 398-5459')
insert into users (FirstName, LastName, Email, Phone) values ('Eugene', 'Perez', 'Dynazzy', '(116) 859-1055')
insert into users (FirstName, LastName, Email, Phone) values ('Laura', 'Evans', 'Dablist', '(334) 191-9844')
insert into users (FirstName, LastName, Email, Phone) values ('Pamela', 'Ryan', 'Zoomlounge', '(334) 311-9596')
insert into users (FirstName, LastName, Email, Phone) values ('Julia', 'Wright', 'Edgepulse', '(415) 594-1316')
insert into users (FirstName, LastName, Email, Phone) values ('Raymond', 'Johnson', 'Skinix', '(364) 782-5037')
insert into users (FirstName, LastName, Email, Phone) values ('Janet', 'Ward', 'Ooba', '(382) 249-3198')
insert into users (FirstName, LastName, Email, Phone) values ('Ashley', 'Simmons', 'Jetpulse', '(371) 499-3723')
insert into users (FirstName, LastName, Email, Phone) values ('Thomas', 'West', 'Fanoodle', '(801) 426-1849')
insert into users (FirstName, LastName, Email, Phone) values ('Elizabeth', 'Price', 'Skynoodle', '(299) 257-8458')
insert into users (FirstName, LastName, Email, Phone) values ('Jean', 'Wallace', 'Fivebridge', '(967) 200-2245')
insert into users (FirstName, LastName, Email, Phone) values ('Bobby', 'Jones', 'Trunyx', '(699) 719-4380')
insert into users (FirstName, LastName, Email, Phone) values ('Jack', 'Shaw', 'Fliptune', '(918) 555-9725')
insert into users (FirstName, LastName, Email, Phone) values ('Joyce', 'Andrews', 'Topicshots', '(188) 631-5817')
insert into users (FirstName, LastName, Email, Phone) values ('Brian', 'Daniels', 'Thoughtmix', '(227) 520-7701')
insert into users (FirstName, LastName, Email, Phone) values ('Carolyn', 'White', 'Divavu', '(789) 522-4054')
insert into users (FirstName, LastName, Email, Phone) values ('Kenneth', 'Bailey', 'Feedbug', '(630) 355-1378')
insert into users (FirstName, LastName, Email, Phone) values ('Willie', 'Carr', 'Avaveo', '(535) 604-3064')
insert into users (FirstName, LastName, Email, Phone) values ('Sean', 'Ferguson', 'Janyx', '(470) 324-8151')
insert into users (FirstName, LastName, Email, Phone) values ('Gary', 'Bowman', 'Vimbo', '(311) 325-8908')
insert into users (FirstName, LastName, Email, Phone) values ('Andrea', 'Garcia', 'Mita', '(176) 443-5676')
insert into users (FirstName, LastName, Email, Phone) values ('Bonnie', 'Mendoza', 'Topicblab', '(872) 173-6793')
insert into users (FirstName, LastName, Email, Phone) values ('Karen', 'Hamilton', 'Zoomdog', '(333) 785-5781')
insert into users (FirstName, LastName, Email, Phone) values ('Edward', 'Dunn', 'Zoombox', '(884) 368-3497')
insert into users (FirstName, LastName, Email, Phone) values ('William', 'Owens', 'Topicstorm', '(122) 830-8245')
insert into users (FirstName, LastName, Email, Phone) values ('Jennifer', 'Berry', 'Buzzbean', '(626) 826-3050')
insert into users (FirstName, LastName, Email, Phone) values ('Christine', 'Freeman', 'Mycat', '(132) 158-4444')
insert into users (FirstName, LastName, Email, Phone) values ('Norma', 'Mccoy', 'Ailane', '(310) 300-7377')
insert into users (FirstName, LastName, Email, Phone) values ('Jessica', 'Montgomery', 'Agimba', '(986) 375-4983')
insert into users (FirstName, LastName, Email, Phone) values ('Lawrence', 'Kelly', 'Jaxbean', '(373) 566-3500')
insert into users (FirstName, LastName, Email, Phone) values ('Ruby', 'Brown', 'Demizz', '(202) 621-6775')
insert into users (FirstName, LastName, Email, Phone) values ('Frank', 'Kelley', 'Wordware', '(211) 622-4228')
insert into users (FirstName, LastName, Email, Phone) values ('Denise', 'Perkins', 'Eayo', '(654) 720-1730')
insert into users (FirstName, LastName, Email, Phone) values ('Rebecca', 'Fisher', 'Shufflebeat', '(943) 614-8535')
insert into users (FirstName, LastName, Email, Phone) values ('Terry', 'Murphy', 'Wikizz', '(745) 281-5643')
insert into users (FirstName, LastName, Email, Phone) values ('David', 'Powell', 'Yoveo', '(617) 876-9423')
insert into users (FirstName, LastName, Email, Phone) values ('Earl', 'Cruz', 'Gabtune', '(934) 914-9000')
insert into users (FirstName, LastName, Email, Phone) values ('Marie', 'Bishop', 'Layo', '(435) 496-8341')
insert into users (FirstName, LastName, Email, Phone) values ('Jeremy', 'Medina', 'Skalith', '(455) 138-5272')
insert into users (FirstName, LastName, Email, Phone) values ('Juan', 'Welch', 'Fatz', '(941) 263-1126')
insert into users (FirstName, LastName, Email, Phone) values ('Martin', 'Nguyen', 'Twitterworks', '(418) 128-8964')
insert into users (FirstName, LastName, Email, Phone) values ('Evelyn', 'Hall', 'Fiveclub', '(995) 832-1775')
insert into users (FirstName, LastName, Email, Phone) values ('Daniel', 'Wood', 'Flashset', '(705) 579-1505')
insert into users (FirstName, LastName, Email, Phone) values ('Ryan', 'Burke', 'Youspan', '(676) 924-9644')
insert into users (FirstName, LastName, Email, Phone) values ('Amanda', 'Willis', 'Yakitri', '(712) 958-5433')
insert into users (FirstName, LastName, Email, Phone) values ('Billy', 'Romero', 'Vitz', '(692) 200-2085')
insert into users (FirstName, LastName, Email, Phone) values ('Frances', 'Sims', 'Browsetype', '(821) 359-6227')
insert into users (FirstName, LastName, Email, Phone) values ('Doris', 'Bradley', 'Quimba', '(485) 692-2681')
insert into users (FirstName, LastName, Email, Phone) values ('Benjamin', 'Hill', 'Devify', '(397) 681-6109')
insert into users (FirstName, LastName, Email, Phone) values ('Robin', 'Henry', 'Gabspot', '(492) 406-9073')
insert into users (FirstName, LastName, Email, Phone) values ('Gloria', 'Thompson', 'Wordtune', '(431) 863-4783')
insert into users (FirstName, LastName, Email, Phone) values ('Angela', 'Hanson', 'Blognation', '(184) 951-7487')
insert into users (FirstName, LastName, Email, Phone) values ('Emily', 'Hughes', 'Avamba', '(492) 690-5009')
insert into users (FirstName, LastName, Email, Phone) values ('Scott', 'Johnston', 'Cogibox', '(249) 789-2748')
insert into users (FirstName, LastName, Email, Phone) values ('Anna', 'Collins', 'Feedfire', '(387) 108-3675')
insert into users (FirstName, LastName, Email, Phone) values ('Rose', 'Castillo', 'Rhyzio', '(128) 405-3604')
insert into users (FirstName, LastName, Email, Phone) values ('Jerry', 'Stevens', 'Meembee', '(501) 524-5368')
insert into users (FirstName, LastName, Email, Phone) values ('Albert', 'Hunt', 'Midel', '(430) 773-3423')
insert into users (FirstName, LastName, Email, Phone) values ('Ruth', 'Kennedy', 'Livefish', '(963) 590-3144')
insert into users (FirstName, LastName, Email, Phone) values ('Betty', 'Lawrence', 'Jaxnation', '(968) 492-5454')
insert into users (FirstName, LastName, Email, Phone) values ('Justin', 'Bell', 'Plambee', '(107) 672-1298')
insert into users (FirstName, LastName, Email, Phone) values ('Donna', 'Woods', 'Eadel', '(687) 444-9935')
insert into users (FirstName, LastName, Email, Phone) values ('Ronald', 'Campbell', 'Photolist', '(960) 519-5485')
insert into users (FirstName, LastName, Email, Phone) values ('Ralph', 'Robinson', 'Babbleopia', '(233) 433-2377')
insert into users (FirstName, LastName, Email, Phone) values ('Julie', 'Stephens', 'Zoovu', '(935) 599-1719')
insert into users (FirstName, LastName, Email, Phone) values ('Henry', 'Hernandez', 'Realcube', '(812) 740-7195')
insert into users (FirstName, LastName, Email, Phone) values ('Robert', 'Green', 'Trudoo', '(312) 302-8049')
insert into users (FirstName, LastName, Email, Phone) values ('Paula', 'Sanchez', 'Roombo', '(313) 871-5961')
insert into users (FirstName, LastName, Email, Phone) values ('Maria', 'Moore', 'Zooveo', '(552) 644-4534')
insert into users (FirstName, LastName, Email, Phone) values ('Christina', 'Stone', 'Flipstorm', '(349) 933-8998')
insert into users (FirstName, LastName, Email, Phone) values ('Shirley', 'Hart', 'Blogtags', '(419) 179-9474')
insert into users (FirstName, LastName, Email, Phone) values ('Cynthia', 'Sanders', 'Thoughtbeat', '(196) 447-7013')
insert into users (FirstName, LastName, Email, Phone) values ('Steve', 'Wheeler', 'Jamia', '(140) 527-5054')
insert into users (FirstName, LastName, Email, Phone) values ('Joe', 'Kim', 'Meemm', '(708) 739-4195')
insert into users (FirstName, LastName, Email, Phone) values ('Tammy', 'Garrett', 'Myworks', '(174) 570-1929')
insert into users (FirstName, LastName, Email, Phone) values ('Jonathan', 'King', 'Skidoo', '(142) 822-4293')
insert into users (FirstName, LastName, Email, Phone) values ('Mary', 'Austin', 'Fivespan', '(481) 303-5031')
insert into users (FirstName, LastName, Email, Phone) values ('Lori', 'Arnold', 'Vipe', '(605) 124-2476')
insert into users (FirstName, LastName, Email, Phone) values ('Craig', 'Coleman', 'Zazio', '(644) 270-3255')
insert into users (FirstName, LastName, Email, Phone) values ('Patrick', 'Anderson', 'Voomm', '(791) 588-1225')
insert into users (FirstName, LastName, Email, Phone) values ('Debra', 'Cook', 'Oozz', '(422) 892-1300')
insert into users (FirstName, LastName, Email, Phone) values ('Keith', 'Robertson', 'Thoughtbridge', '(644) 855-7735')
insert into users (FirstName, LastName, Email, Phone) values ('Teresa', 'Jenkins', 'Quatz', '(883) 117-9477')
insert into users (FirstName, LastName, Email, Phone) values ('Arthur', 'Stanley', 'Youbridge', '(478) 195-9998')
insert into users (FirstName, LastName, Email, Phone) values ('Larry', 'Long', 'Vidoo', '(555) 163-6023')
insert into users (FirstName, LastName, Email, Phone) values ('Joseph', 'Graham', 'Wikivu', '(957) 244-2925')
insert into users (FirstName, LastName, Email, Phone) values ('Eric', 'Cooper', 'Aivee', '(175) 392-4177')
insert into users (FirstName, LastName, Email, Phone) values ('Stephen', 'Duncan', 'Dabshots', '(504) 408-8525')
insert into users (FirstName, LastName, Email, Phone) values ('Carol', 'Pierce', 'Oyope', '(472) 545-1045')
insert into users (FirstName, LastName, Email, Phone) values ('Stephanie', 'Knight', 'Meedoo', '(849) 686-3546')
insert into users (FirstName, LastName, Email, Phone) values ('Nancy', 'Reid', 'Photobug', '(949) 321-6327')
insert into users (FirstName, LastName, Email, Phone) values ('Theresa', 'Riley', 'Kazu', '(457) 490-2967')
insert into users (FirstName, LastName, Email, Phone) values ('Anthony', 'Stewart', 'Linklinks', '(234) 781-9560')
insert into users (FirstName, LastName, Email, Phone) values ('Randy', 'Webb', 'Centimia', '(991) 613-8547')
insert into users (FirstName, LastName, Email, Phone) values ('Brandon', 'Rose', 'Einti', '(216) 134-5585')
insert into users (FirstName, LastName, Email, Phone) values ('Carlos', 'Carter', 'Tanoodle', '(498) 241-6135')
insert into users (FirstName, LastName, Email, Phone) values ('Wanda', 'Gomez', 'Meetz', '(186) 102-7616')
insert into users (FirstName, LastName, Email, Phone) values ('Clarence', 'Young', 'Fadeo', '(467) 919-8249')
insert into users (FirstName, LastName, Email, Phone) values ('Patricia', 'Barnes', 'Feedfish', '(815) 577-1873')
insert into users (FirstName, LastName, Email, Phone) values ('Jason', 'Walker', 'Wordpedia', '(876) 738-8110')
insert into users (FirstName, LastName, Email, Phone) values ('Catherine', 'Payne', 'Trudeo', '(757) 137-8930')
insert into users (FirstName, LastName, Email, Phone) values ('Sandra', 'Gonzalez', 'Chatterpoint', '(885) 823-9700')
insert into users (FirstName, LastName, Email, Phone) values ('Annie', 'Ray', 'Browsecat', '(165) 315-2288')
insert into users (FirstName, LastName, Email, Phone) values ('Cheryl', 'Reyes', 'Linktype', '(928) 130-6648')
insert into users (FirstName, LastName, Email, Phone) values ('Louis', 'Richardson', 'Aimbu', '(963) 698-4859')
insert into users (FirstName, LastName, Email, Phone) values ('Kelly', 'Howell', 'Feedspan', '(638) 813-8423')
insert into users (FirstName, LastName, Email, Phone) values ('Victor', 'Weaver', 'Skivee', '(426) 423-8294')
insert into users (FirstName, LastName, Email, Phone) values ('Mark', 'Little', 'Lazzy', '(494) 969-9550')
insert into users (FirstName, LastName, Email, Phone) values ('Linda', 'Gonzales', 'Rhynyx', '(301) 759-1117')
insert into users (FirstName, LastName, Email, Phone) values ('Deborah', 'Harris', 'Gabtype', '(132) 621-1779')
insert into users (FirstName, LastName, Email, Phone) values ('Diana', 'Oliver', 'Meeveo', '(529) 593-1785')
insert into users (FirstName, LastName, Email, Phone) values ('Richard', 'Baker', 'Jayo', '(295) 636-6308')
insert into users (FirstName, LastName, Email, Phone) values ('Barbara', 'Howard', 'Blogtag', '(106) 372-1760')
insert into users (FirstName, LastName, Email, Phone) values ('Diane', 'Harvey', 'Skiba', '(477) 324-7935')
insert into users (FirstName, LastName, Email, Phone) values ('Louise', 'Taylor', 'Twimm', '(239) 547-2431')
insert into users (FirstName, LastName, Email, Phone) values ('Jeffrey', 'Tucker', 'Oodoo', '(628) 575-1488')
insert into users (FirstName, LastName, Email, Phone) values ('Brenda', 'Morrison', 'Gabvine', '(665) 619-4651')
insert into users (FirstName, LastName, Email, Phone) values ('Kathryn', 'Watkins', 'Kimia', '(651) 309-2577')
insert into users (FirstName, LastName, Email, Phone) values ('Dorothy', 'Frazier', 'Twitterwire', '(610) 945-2120')
insert into users (FirstName, LastName, Email, Phone) values ('Roger', 'Cunningham', 'Oloo', '(746) 973-2132')
insert into users (FirstName, LastName, Email, Phone) values ('Aaron', 'Reed', 'Dynava', '(584) 310-3241')
insert into users (FirstName, LastName, Email, Phone) values ('Lillian', 'Dean', 'Rhyloo', '(227) 456-1798')
insert into users (FirstName, LastName, Email, Phone) values ('Charles', 'Foster', 'Cogidoo', '(471) 958-9002')
insert into users (FirstName, LastName, Email, Phone) values ('Donald', 'Lewis', 'Lajo', '(248) 615-8064')
insert into users (FirstName, LastName, Email, Phone) values ('Adam', 'Rogers', 'Dazzlesphere', '(576) 775-3713')
insert into users (FirstName, LastName, Email, Phone) values ('Russell', 'Chavez', 'Mydeo', '(630) 325-6212')
insert into users (FirstName, LastName, Email, Phone) values ('Sara', 'Martin', 'DabZ', '(620) 638-5615')
insert into users (FirstName, LastName, Email, Phone) values ('Phillip', 'Palmer', 'Miboo', '(131) 310-6136')
insert into users (FirstName, LastName, Email, Phone) values ('Kathleen', 'Burns', 'Linkbridge', '(452) 828-4959')
insert into users (FirstName, LastName, Email, Phone) values ('Lisa', 'Washington', 'Yodel', '(835) 853-6561')
insert into users (FirstName, LastName, Email, Phone) values ('Irene', 'Cox', 'Oyoba', '(515) 259-7182')
insert into users (FirstName, LastName, Email, Phone) values ('Carl', 'Mills', 'Tambee', '(348) 335-2485')
insert into users (FirstName, LastName, Email, Phone) values ('Harry', 'Edwards', 'Leenti', '(612) 165-8607')
insert into users (FirstName, LastName, Email, Phone) values ('Lois', 'Snyder', 'Gigazoom', '(587) 455-7615')
insert into users (FirstName, LastName, Email, Phone) values ('Jane', 'Diaz', 'Roodel', '(853) 219-4997')
insert into users (FirstName, LastName, Email, Phone) values ('Amy', 'Mitchell', 'Voonte', '(193) 391-7964')
insert into users (FirstName, LastName, Email, Phone) values ('Margaret', 'Phillips', 'Kanoodle', '(122) 290-5465')
insert into users (FirstName, LastName, Email, Phone) values ('Anne', 'Harper', 'Skinte', '(849) 799-5383')
insert into users (FirstName, LastName, Email, Phone) values ('Melissa', 'Ellis', 'Babblestorm', '(110) 922-6582')
insert into users (FirstName, LastName, Email, Phone) values ('Jose', 'Mason', 'Yodoo', '(227) 827-3555')
insert into users (FirstName, LastName, Email, Phone) values ('Paul', 'Jacobs', 'Brainbox', '(653) 856-3665')
insert into users (FirstName, LastName, Email, Phone) values ('Michelle', 'Allen', 'Zoombeat', '(225) 554-7561')
insert into users (FirstName, LastName, Email, Phone) values ('John', 'Wilson', 'Tekfly', '(781) 640-1804')
insert into users (FirstName, LastName, Email, Phone) values ('Nicole', 'Rivera', 'Yadel', '(690) 603-2377')
insert into users (FirstName, LastName, Email, Phone) values ('Helen', 'Jordan', 'Photojam', '(372) 797-4219')
insert into users (FirstName, LastName, Email, Phone) values ('George', 'Schmidt', 'Bubblemix', '(576) 852-5470')
insert into users (FirstName, LastName, Email, Phone) values ('Dennis', 'Peterson', 'Skajo', '(482) 407-3305')
insert into users (FirstName, LastName, Email, Phone) values ('Douglas', 'Patterson', 'Centidel', '(456) 324-1889')
insert into users (FirstName, LastName, Email, Phone) values ('Phyllis', 'Miller', 'Gabcube', '(574) 352-7110')
insert into users (FirstName, LastName, Email, Phone) values ('Michael', 'Hudson', 'Zooxo', '(558) 954-8270')
insert into users (FirstName, LastName, Email, Phone) values ('Martha', 'Peters', 'Voonyx', '(320) 921-1975')
insert into users (FirstName, LastName, Email, Phone) values ('Walter', 'Sullivan', 'Flipbug', '(295) 443-8212')
insert into users (FirstName, LastName, Email, Phone) values ('Ann', 'Greene', 'Thoughtstorm', '(946) 772-6527')
insert into users (FirstName, LastName, Email, Phone) values ('Peter', 'Vasquez', 'Browsedrive', '(126) 182-6416')
insert into users (FirstName, LastName, Email, Phone) values ('Kevin', 'Porter', 'Tagopia', '(377) 316-1850')
insert into users (FirstName, LastName, Email, Phone) values ('James', 'Elliott', 'Edgeblab', '(242) 174-1893')
insert into users (FirstName, LastName, Email, Phone) values ('Virginia', 'Gardner', 'Twinder', '(367) 674-2489')
insert into users (FirstName, LastName, Email, Phone) values ('Sarah', 'Fuller', 'Yodo', '(564) 265-2827')
insert into users (FirstName, LastName, Email, Phone) values ('Jesse', 'Marshall', 'Thoughtsphere', '(549) 976-3983')
insert into users (FirstName, LastName, Email, Phone) values ('Nicholas', 'Banks', 'Tagpad', '(976) 766-7393')
insert into users (FirstName, LastName, Email, Phone) values ('Janice', 'Smith', 'Zava', '(216) 665-1226')
insert into users (FirstName, LastName, Email, Phone) values ('Mildred', 'Meyer', 'Npath', '(334) 602-3681')
insert into users (FirstName, LastName, Email, Phone) values ('Gerald', 'Morgan', 'Oba', '(487) 913-3661')
insert into users (FirstName, LastName, Email, Phone) values ('Jacqueline', 'Burton', 'Livepath', '(669) 326-1356')
insert into users (FirstName, LastName, Email, Phone) values ('Shawn', 'Hansen', 'Wordify', '(286) 108-3209')
insert into users (FirstName, LastName, Email, Phone) values ('Judith', 'Holmes', 'Blogpad', '(491) 592-8093')
insert into users (FirstName, LastName, Email, Phone) values ('Beverly', 'Garza', 'Quaxo', '(155) 497-4963')
insert into users (FirstName, LastName, Email, Phone) values ('Roy', 'Gutierrez', 'Vinte', '(359) 795-6277')
insert into users (FirstName, LastName, Email, Phone) values ('Andrew', 'Dixon', 'Jabberstorm', '(222) 928-3349')
insert into users (FirstName, LastName, Email, Phone) values ('Antonio', 'Bennett', 'Dynabox', '(356) 909-2165')
insert into users (FirstName, LastName, Email, Phone) values ('Marilyn', 'Alvarez', 'Talane', '(608) 199-4506')
insert into users (FirstName, LastName, Email, Phone) values ('Alan', 'Davis', 'Trupe', '(249) 496-6198')
insert into users (FirstName, LastName, Email, Phone) values ('Timothy', 'Lopez', 'Dabjam', '(469) 132-9844')
insert into users (FirstName, LastName, Email, Phone) values ('Ernest', 'Cole', 'Skipstorm', '(907) 800-1953')
insert into users (FirstName, LastName, Email, Phone) values ('Howard', 'Fields', 'Zoomcast', '(236) 916-7129')
insert into users (FirstName, LastName, Email, Phone) values ('Bruce', 'Armstrong', 'Realmix', '(978) 366-3399')
insert into users (FirstName, LastName, Email, Phone) values ('Tina', 'Hawkins', 'Avavee', '(383) 708-7729')
insert into users (FirstName, LastName, Email, Phone) values ('Wayne', 'Lawson', 'Dabtype', '(303) 358-2803')
insert into users (FirstName, LastName, Email, Phone) values ('Alice', 'Nichols', 'Kwimbee', '(871) 861-2040')
insert into users (FirstName, LastName, Email, Phone) values ('Judy', 'Ramirez', 'Livetube', '(520) 889-7120')
insert into users (FirstName, LastName, Email, Phone) values ('Matthew', 'Richards', 'Digitube', '(797) 641-1028')
insert into users (FirstName, LastName, Email, Phone) values ('Todd', 'Thomas', 'Aibox', '(735) 298-8984')
insert into users (FirstName, LastName, Email, Phone) values ('Jimmy', 'Morris', 'Browsezoom', '(495) 988-7905')
insert into users (FirstName, LastName, Email, Phone) values ('Joan', 'Mcdonald', 'Voonix', '(835) 494-8670')
go
--Fix the email address to include the first and last name
update users set email = FirstName + '.' + LastName + '@' + Email + '.com'
go
-- Creating address data
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skyvu', '1029', 'Butterfield' + ' Alley', 'Cincinnati', 'AL', '83896')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jaloo', '1034', 'Crowley' + ' Avenue', 'Warren', 'AK', '54369')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Wikibox', '1126', 'Anderson' + ' Center', 'Pittsburgh', 'AZ', '22814')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Meezzy', '1159', 'Kennedy' + ' Circle', 'Gilbert', 'AR', '68979')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Buzzshare', '1227', 'Commercial' + ' Court', 'Decatur', 'CA', '19385')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Teklist', '1241', 'Chive' + ' Crossing', 'Lexington', 'CO', '64070')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Browseblab', '1276', 'Truax' + ' Drive', 'Kansas City', 'CT', '26789')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jaxworks', '1325', 'Hooker' + ' Hill', 'Milwaukee', 'DE', '28591')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Babbleblab', '1332', 'Autumn Leaf' + ' Junction', 'Houston', 'FL', '96040')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Rhybox', '1353', 'Dayton' + ' Lane', 'Toledo', 'GA', '85424')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Wikido', '1403', 'Golf' + ' Park', 'Birmingham', 'HI', '94028')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Lazz', '1428', 'Amoth' + ' Parkway', 'Springfield', 'ID', '66282')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Realfire', '1460', 'Service' + ' Pass', 'Boston', 'IL', '49637')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Realbuzz', '1472', 'Coolidge' + ' Place', 'Salt Lake City', 'IN', '15472')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Minyx', '1498', 'Independence' + ' Plaza', 'Saint Petersburg', 'IA', '73050')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Flashspan', '1580', 'Maple Wood' + ' Point', 'Topeka', 'KS', '95235')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Oyoloo', '1584', 'Forest Dale' + ' Road', 'Jeffersonville', 'KY', '22962')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yamia', '1610', 'Brown' + ' Street', 'Salem', 'LA', '97097')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Bluezoom', '1627', 'Golf Course' + ' Terrace', 'Boston', 'ME', '28083')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Devcast', '1687', 'Spenser' + ' Trail', 'Wichita', 'MD', '45745')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Rhynoodle', '1698', 'Corry' + ' Way', 'San Diego', 'MA', '42641')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yotz', '1783', 'Reindahl' + ' Alley', 'Erie', 'MI', '25393')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Devpoint', '1803', 'Emmet' + ' Avenue', 'Mountain View', 'MN', '55226')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jetwire', '1856', 'Di Loreto' + ' Center', 'Riverside', 'MS', '34380')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Babbleset', '1892', 'Hollow Ridge' + ' Circle', 'Roanoke', 'MO', '70744')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skyndu', '2020', 'Alpine' + ' Court', 'Springfield', 'MT', '60711')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Pixope', '2054', 'Lyons' + ' Crossing', 'Clearwater', 'NE', '74660')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Demimbu', '2064', 'Knutson' + ' Drive', 'Colorado Springs', 'NV', '97693')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Flashpoint', '2082', 'Arapahoe' + ' Hill', 'Arlington', 'NH', '62590')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Innojam', '2108', 'Hoffman' + ' Junction', 'New York City', 'NJ', '99665')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Eidel', '2119', 'Vera' + ' Lane', 'Grand Forks', 'NM', '96581')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Rooxo', '2120', 'Glacier Hill' + ' Park', 'Washington', 'NY', '49589')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Mynte', '2184', 'Scott' + ' Parkway', 'Saint Cloud', 'NC', '10832')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Oyonder', '2228', 'Jay' + ' Pass', 'New York City', 'ND', '51818')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Realbridge', '2232', 'Roxbury' + ' Place', 'Aurora', 'OH', '65836')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Aimbo', '2234', 'Pawling' + ' Plaza', 'Worcester', 'OK', '52768')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Ntags', '2243', 'Manitowish' + ' Point', 'Bakersfield', 'OR', '63454')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skiptube', '2250', 'Michigan' + ' Road', 'Fort Lauderdale', 'PA', '21042')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skaboo', '2268', 'Mendota' + ' Street', 'New York City', 'RI', '61659')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Innotype', '2368', 'Jenifer' + ' Terrace', 'Minneapolis', 'SC', '94401')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Youfeed', '2384', 'Forster' + ' Trail', 'Saint Louis', 'SD', '15327')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Leexo', '2425', 'Gerald' + ' Way', 'Fort Worth', 'TN', '22273')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Bubblebox', '2463', '5th' + ' Alley', 'Sacramento', 'TX', '37320')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Eabox', '2488', 'Northland' + ' Avenue', 'Pittsburgh', 'UT', '14071')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Snaptags', '2574', 'Oakridge' + ' Center', 'Spokane', 'VT', '79841')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Edgewire', '2606', 'Barnett' + ' Circle', 'Tacoma', 'VA', '38700')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yakijo', '2619', 'Hallows' + ' Court', 'Asheville', 'WA', '96047')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Photospace', '2647', 'Ridgeview' + ' Crossing', 'New Orleans', 'WV', '63729')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yacero', '2661', 'Karstens' + ' Drive', 'Topeka', 'WI', '75164')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jabbercube', '2758', 'Mifflin' + ' Hill', 'Lexington', 'WY', '78869')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kwinu', '2766', 'Clyde Gallagher' + ' Junction', 'Boston', 'AL', '29505')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skilith', '2780', 'Randy' + ' Lane', 'Philadelphia', 'AK', '48715')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Agivu', '2802', 'Pleasure' + ' Park', 'Dallas', 'AZ', '79461')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('JumpXS', '2832', 'Northview' + ' Parkway', 'Detroit', 'AR', '80029')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tavu', '2838', 'Harbort' + ' Pass', 'North Las Vegas', 'CA', '52337')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Edgetag', '2874', 'Butternut' + ' Place', 'Cincinnati', 'CO', '66924')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Chatterbridge', '2897', 'Manley' + ' Plaza', 'Phoenix', 'CT', '45171')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('InnoZ', '3064', 'Walton' + ' Point', 'Columbia', 'DE', '97876')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dynazzy', '3094', 'Reinke' + ' Road', 'Seattle', 'FL', '32735')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dablist', '3100', 'Darwin' + ' Street', 'Scranton', 'GA', '18375')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zoomlounge', '3120', 'Schurz' + ' Terrace', 'Riverside', 'HI', '22194')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Edgepulse', '3260', 'Huxley' + ' Trail', 'Washington', 'ID', '82704')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skinix', '3308', 'Stang' + ' Way', 'Greensboro', 'IL', '79054')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Ooba', '3328', 'Troy' + ' Alley', 'Philadelphia', 'IN', '59341')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jetpulse', '3374', 'Cambridge' + ' Avenue', 'Oakland', 'IA', '11643')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Fanoodle', '3440', 'Bartelt' + ' Center', 'Modesto', 'KS', '95345')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skynoodle', '3444', 'Scoville' + ' Circle', 'Sacramento', 'KY', '24820')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Fivebridge', '3514', 'Park Meadow' + ' Court', 'Brooklyn', 'LA', '95838')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Trunyx', '3527', 'Waxwing' + ' Crossing', 'Fort Worth', 'ME', '81640')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Fliptune', '3543', 'Browning' + ' Drive', 'Spokane', 'MD', '17438')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Topicshots', '3548', 'Warrior' + ' Hill', 'Salt Lake City', 'MA', '34029')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Thoughtmix', '3803', 'Crest Line' + ' Junction', 'Pittsburgh', 'MI', '98276')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Divavu', '3861', '4th' + ' Lane', 'Norfolk', 'MN', '59255')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Feedbug', '3915', 'Susan' + ' Park', 'Sacramento', 'MS', '31484')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Avaveo', '3919', 'Dottie' + ' Parkway', 'Virginia Beach', 'MO', '55408')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Janyx', '3976', 'Sugar' + ' Pass', 'Jamaica', 'MT', '71289')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Vimbo', '4008', 'Fairfield' + ' Place', 'Washington', 'NE', '86662')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Mita', '4046', 'Debs' + ' Plaza', 'Boise', 'NV', '26222')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Topicblab', '4063', 'Dixon' + ' Point', 'Littleton', 'NH', '68121')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zoomdog', '4072', 'Transport' + ' Road', 'Saginaw', 'NJ', '73081')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zoombox', '4073', 'Red Cloud' + ' Street', 'Springfield', 'NM', '44698')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Topicstorm', '4136', 'Cardinal' + ' Terrace', 'Fresno', 'NY', '78040')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Buzzbean', '4157', 'Bluejay' + ' Trail', 'Fort Pierce', 'NC', '96548')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Mycat', '4177', 'Oak' + ' Way', 'El Paso', 'ND', '50320')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Ailane', '4197', 'Fremont' + ' Alley', 'El Paso', 'OH', '60488')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Agimba', '4210', '1st' + ' Avenue', 'Evanston', 'OK', '85637')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jaxbean', '4218', 'West' + ' Center', 'Spartanburg', 'OR', '94755')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Demizz', '4230', 'Vahlen' + ' Circle', 'Washington', 'PA', '39749')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Wordware', '4243', 'Village Green' + ' Court', 'Birmingham', 'RI', '16911')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Eayo', '4253', 'Pearson' + ' Crossing', 'Tulsa', 'SC', '22207')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Shufflebeat', '4331', 'Sullivan' + ' Drive', 'Indianapolis', 'SD', '98512')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Wikizz', '4408', 'Spohn' + ' Hill', 'Anchorage', 'TN', '68886')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yoveo', '4414', 'Mesta' + ' Junction', 'New York City', 'TX', '33846')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Gabtune', '4425', 'La Follette' + ' Lane', 'Washington', 'UT', '21335')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Layo', '4442', 'Meadow Ridge' + ' Park', 'New Orleans', 'VT', '45857')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skalith', '4463', 'Lakeland' + ' Parkway', 'Reno', 'VA', '71844')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Fatz', '4475', 'Nancy' + ' Pass', 'Pittsburgh', 'WA', '86836')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Twitterworks', '4490', 'Caliangt' + ' Place', 'Colorado Springs', 'WV', '18437')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Fiveclub', '4565', 'Anniversary' + ' Plaza', 'El Paso', 'WI', '97351')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Flashset', '4600', 'Kensington' + ' Point', 'Worcester', 'WY', '13650')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Youspan', '4628', 'Lighthouse Bay' + ' Road', 'San Antonio', 'AL', '70799')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yakitri', '4637', 'Elmside' + ' Street', 'Washington', 'AK', '36968')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Vitz', '4647', 'Shopko' + ' Terrace', 'Philadelphia', 'AZ', '25032')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Browsetype', '4721', 'Jana' + ' Trail', 'San Diego', 'AR', '72701')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Quimba', '4759', 'Crescent Oaks' + ' Way', 'New York City', 'CA', '24383')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Devify', '4779', 'Thompson' + ' Alley', 'Lakeland', 'CO', '95482')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Gabspot', '4795', 'Bellgrove' + ' Avenue', 'Fresno', 'CT', '94722')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Wordtune', '4796', 'Ridge Oak' + ' Center', 'Lees Summit', 'DE', '62788')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Blognation', '4840', 'Linden' + ' Circle', 'El Paso', 'FL', '60682')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Avamba', '4869', 'Corscot' + ' Court', 'Shawnee Mission', 'GA', '48132')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Cogibox', '4914', 'Center' + ' Crossing', 'Fullerton', 'HI', '42138')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Feedfire', '4997', 'Roth' + ' Drive', 'Greensboro', 'ID', '16737')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Rhyzio', '5051', 'Loftsgordon' + ' Hill', 'Los Angeles', 'IL', '64953')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Meembee', '5076', 'Southridge' + ' Junction', 'Austin', 'IN', '41509')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Midel', '5096', 'Erie' + ' Lane', 'Atlanta', 'IA', '43184')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Livefish', '5140', 'Columbus' + ' Park', 'Bakersfield', 'KS', '45884')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jaxnation', '5181', 'Wayridge' + ' Parkway', 'Brooklyn', 'KY', '93718')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Plambee', '5275', 'Jenna' + ' Pass', 'Seattle', 'LA', '42172')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Eadel', '5404', 'Starling' + ' Place', 'Orlando', 'ME', '85030')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Photolist', '5435', 'Raven' + ' Plaza', 'New Orleans', 'MD', '51967')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Babbleopia', '5598', 'Melody' + ' Point', 'Hampton', 'MA', '98958')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zoovu', '5633', 'Aberg' + ' Road', 'Augusta', 'MI', '54744')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Realcube', '5717', 'Gale' + ' Street', 'Philadelphia', 'MN', '72119')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Trudoo', '5800', 'Johnson' + ' Terrace', 'New York City', 'MS', '83642')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Roombo', '5812', 'Veith' + ' Trail', 'Amarillo', 'MO', '34259')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zooveo', '5831', 'Arkansas' + ' Way', 'Melbourne', 'MT', '93288')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Flipstorm', '5860', 'Nova' + ' Alley', 'Long Beach', 'NE', '34438')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Blogtags', '5923', 'Arizona' + ' Avenue', 'Richmond', 'NV', '30013')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Thoughtbeat', '5934', 'Steensland' + ' Center', 'Albuquerque', 'NH', '27061')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jamia', '5937', 'Sunbrook' + ' Circle', 'Dallas', 'NJ', '65145')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Meemm', '5948', 'Bashford' + ' Court', 'Washington', 'NM', '75645')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Myworks', '6009', '2nd' + ' Crossing', 'Charleston', 'NY', '45570')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skidoo', '6043', 'Lukken' + ' Drive', 'Athens', 'NC', '99711')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Fivespan', '6057', 'Magdeline' + ' Hill', 'Tampa', 'ND', '62812')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Vipe', '6133', 'Scofield' + ' Junction', 'Schaumburg', 'OH', '63327')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zazio', '6152', 'Rockefeller' + ' Lane', 'Buffalo', 'OK', '10587')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Voomm', '6165', 'Meadow Vale' + ' Park', 'San Diego', 'OR', '48482')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Oozz', '6175', 'Calypso' + ' Parkway', 'Fort Worth', 'PA', '95706')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Thoughtbridge', '6227', 'Bayside' + ' Pass', 'Richmond', 'RI', '81749')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Quatz', '6250', 'Farragut' + ' Place', 'Lexington', 'SC', '16536')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Youbridge', '6267', 'Marquette' + ' Plaza', 'Mc Keesport', 'SD', '76987')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Vidoo', '6439', 'Fieldstone' + ' Point', 'Champaign', 'TN', '19500')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Wikivu', '6494', 'Homewood' + ' Road', 'Salt Lake City', 'TX', '32379')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Aivee', '6522', 'Jackson' + ' Street', 'Houston', 'UT', '33405')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dabshots', '6567', 'Mcguire' + ' Terrace', 'Trenton', 'VT', '97555')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Oyope', '6629', '6th' + ' Trail', 'Orlando', 'VA', '95517')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Meedoo', '6888', 'Pierstorff' + ' Way', 'Boise', 'WA', '36568')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Photobug', '6894', 'Almo' + ' Alley', 'Des Moines', 'WV', '55319')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kazu', '6923', 'Tennessee' + ' Avenue', 'Honolulu', 'WI', '44990')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Linklinks', '6962', 'Kingsford' + ' Center', 'Rochester', 'WY', '49331')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Centimia', '6966', 'Atwood' + ' Circle', 'Atlanta', 'AL', '25650')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Einti', '6990', 'Mitchell' + ' Court', 'Atlanta', 'AK', '11855')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tanoodle', '7043', 'Lakewood' + ' Crossing', 'Philadelphia', 'AZ', '35608')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Meetz', '7044', 'Dryden' + ' Drive', 'Naples', 'AR', '88663')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Fadeo', '7087', 'Northfield' + ' Hill', 'Terre Haute', 'CA', '95450')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Feedfish', '7116', 'Artisan' + ' Junction', 'Memphis', 'CO', '79417')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Wordpedia', '7122', 'Everett' + ' Lane', 'Des Moines', 'CT', '72499')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Trudeo', '7128', 'Debra' + ' Park', 'Saint Joseph', 'DE', '65920')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Chatterpoint', '7199', 'Dovetail' + ' Parkway', 'Pueblo', 'FL', '63849')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Browsecat', '7224', 'Porter' + ' Pass', 'Boca Raton', 'GA', '67222')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Linktype', '7228', 'Weeping Birch' + ' Place', 'Houston', 'HI', '96967')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Aimbu', '7260', 'Waubesa' + ' Plaza', 'Raleigh', 'ID', '92798')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Feedspan', '7284', 'Towne' + ' Point', 'Atlanta', 'IL', '99910')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skivee', '7288', '3rd' + ' Road', 'Athens', 'IN', '80831')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Lazzy', '7354', 'Dapin' + ' Street', 'Silver Spring', 'IA', '41604')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Rhynyx', '7383', 'Prairie Rose' + ' Terrace', 'Savannah', 'KS', '36468')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Gabtype', '7442', 'Welch' + ' Trail', 'Ashburn', 'KY', '74265')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Meeveo', '7487', 'Toban' + ' Way', 'Charlotte', 'LA', '37081')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jayo', '7521', 'Claremont' + ' Alley', 'Jacksonville', 'ME', '67524')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Blogtag', '7559', 'Glendale' + ' Avenue', 'Houston', 'MD', '98141')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skiba', '7577', 'Comanche' + ' Center', 'Kalamazoo', 'MA', '43959')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Twimm', '7600', 'Cordelia' + ' Circle', 'Raleigh', 'MI', '36977')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Oodoo', '7725', 'Lillian' + ' Court', 'Torrance', 'MN', '27029')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Gabvine', '7733', 'Upham' + ' Crossing', 'Denver', 'MS', '71784')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kimia', '7776', 'Anhalt' + ' Drive', 'Roanoke', 'MO', '83815')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Twitterwire', '7796', 'Cody' + ' Hill', 'Charlotte', 'MT', '66791')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Oloo', '7864', 'Moulton' + ' Junction', 'Raleigh', 'NE', '30185')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dynava', '8039', 'Gulseth' + ' Lane', 'Pueblo', 'NV', '60823')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Rhyloo', '8068', 'Sherman' + ' Park', 'New Orleans', 'NH', '97255')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Cogidoo', '8069', 'Fair Oaks' + ' Parkway', 'Irvine', 'NJ', '30966')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Lajo', '8177', 'Graedel' + ' Pass', 'Fort Lauderdale', 'NM', '51716')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dazzlesphere', '8283', 'Coleman' + ' Place', 'Washington', 'NY', '90829')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Mydeo', '8285', 'Burning Wood' + ' Plaza', 'El Paso', 'NC', '51270')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('DabZ', '8295', 'Mccormick' + ' Point', 'Dallas', 'ND', '59244')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Miboo', '8332', 'Hoard' + ' Road', 'Dallas', 'OH', '94671')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Linkbridge', '8349', 'Havey' + ' Street', 'New York City', 'OK', '54362')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yodel', '8379', 'Talisman' + ' Terrace', 'Miami', 'OR', '10975')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Oyoba', '8429', 'Rigney' + ' Trail', 'Birmingham', 'PA', '76240')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tambee', '8514', 'Mayfield' + ' Way', 'New Castle', 'RI', '11590')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Leenti', '8525', 'Eagan' + ' Alley', 'Reno', 'SC', '92164')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Gigazoom', '8600', 'Mcbride' + ' Avenue', 'Phoenix', 'SD', '36831')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Roodel', '8753', 'Lunder' + ' Center', 'Dayton', 'TN', '27183')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Voonte', '8760', 'Carioca' + ' Circle', 'Denver', 'TX', '61534')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kanoodle', '8768', 'Haas' + ' Court', 'Las Vegas', 'UT', '18623')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skinte', '8834', 'Loomis' + ' Crossing', 'Austin', 'VT', '92648')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Babblestorm', '8867', 'Colorado' + ' Drive', 'Huntsville', 'VA', '44585')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yodoo', '8954', 'Cascade' + ' Hill', 'Oakland', 'WA', '62048')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Brainbox', '9093', 'Farmco' + ' Junction', 'Portsmouth', 'WV', '44444')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zoombeat', '9110', 'Sauthoff' + ' Lane', 'Erie', 'WI', '15658')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tekfly', '9129', 'Donald' + ' Park', 'San Diego', 'WY', '47429')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yadel', '9208', 'Mandrake' + ' Parkway', 'York', 'AL', '73187')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Photojam', '9235', 'Longview' + ' Pass', 'Grand Rapids', 'AK', '18872')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Bubblemix', '9246', 'Pennsylvania' + ' Place', 'Pittsburgh', 'AZ', '26531')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skajo', '9336', 'Leroy' + ' Plaza', 'Las Vegas', 'AR', '72640')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Centidel', '9374', 'Morningstar' + ' Point', 'Hot Springs National Park', 'CA', '63825')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Gabcube', '9433', 'Bonner' + ' Road', 'Winter Haven', 'CO', '44539')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zooxo', '9479', 'Harper' + ' Street', 'Northridge', 'CT', '16732')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Voonyx', '9583', 'Hazelcrest' + ' Terrace', 'Mansfield', 'DE', '70246')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Flipbug', '9599', 'Quincy' + ' Trail', 'Albany', 'FL', '97073')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Thoughtstorm', '9613', 'Vernon' + ' Way', 'Wilkes Barre', 'GA', '53932')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Browsedrive', '9682', 'Maryland' + ' Alley', 'Minneapolis', 'HI', '35069')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tagopia', '9705', 'Sycamore' + ' Avenue', 'Harrisburg', 'ID', '43736')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Edgeblab', '9772', 'Eastwood' + ' Center', 'San Antonio', 'IL', '54453')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Twinder', '9914', 'Hoepker' + ' Circle', 'Memphis', 'IN', '97199')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yodo', '9964', 'Beilfuss' + ' Court', 'Atlanta', 'IA', '11326')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Thoughtsphere', '9969', 'Stuart' + ' Crossing', 'New York City', 'KS', '16285')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tagpad', '9987', 'Lotheville' + ' Drive', 'Portsmouth', 'KY', '92737')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zava', '9994', 'Declaration' + ' Hill', 'Raleigh', 'LA', '63686')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Npath', '1029', 'New Castle' + ' Junction', 'El Paso', 'ME', '17048')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Oba', '1034', 'Kenwood' + ' Lane', 'Orlando', 'MD', '99958')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Livepath', '1126', 'Clemons' + ' Park', 'Prescott', 'MA', '72192')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Wordify', '1159', 'Esker' + ' Parkway', 'Oklahoma City', 'MI', '99296')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Blogpad', '1227', 'Fulton' + ' Pass', 'Los Angeles', 'MN', '81763')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Quaxo', '1241', 'Evergreen' + ' Place', 'Decatur', 'MS', '84454')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Vinte', '1276', 'Mosinee' + ' Plaza', 'Pasadena', 'MO', '79522')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jabberstorm', '1325', 'Westend' + ' Point', 'Peoria', 'MT', '38133')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dynabox', '1332', 'Algoma' + ' Road', 'Baton Rouge', 'NE', '71660')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Talane', '1353', 'Mallard' + ' Street', 'Rochester', 'NV', '74570')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Trupe', '1403', 'Rutledge' + ' Terrace', 'Carlsbad', 'NH', '44175')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dabjam', '1428', 'Fallview' + ' Trail', 'Chattanooga', 'NJ', '13382')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skipstorm', '1460', 'Katie' + ' Way', 'Jacksonville', 'NM', '30818')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zoomcast', '1472', 'Ridgeway' + ' Alley', 'Morgantown', 'NY', '89076')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Realmix', '1498', 'Springview' + ' Avenue', 'New York City', 'NC', '79933')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Avavee', '1580', 'Holmberg' + ' Center', 'Oklahoma City', 'ND', '27787')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dabtype', '1584', 'Nobel' + ' Circle', 'Grand Junction', 'OH', '55086')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kwimbee', '1610', 'Messerschmidt' + ' Court', 'Boise', 'OK', '72614')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Livetube', '1627', 'Northwestern' + ' Crossing', 'Pasadena', 'OR', '54659')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Digitube', '1687', 'Lake View' + ' Drive', 'Dayton', 'PA', '25557')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Aibox', '1698', 'Sunnyside' + ' Hill', 'Great Neck', 'RI', '22787')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Browsezoom', '1783', 'International' + ' Junction', 'Toledo', 'SC', '47629')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Voonix', '1803', 'Sage' + ' Lane', 'Shawnee Mission', 'SD', '74505')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Gevee', '1856', 'Tennyson' + ' Park', 'Seattle', 'TN', '42561')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jaxspan', '1892', 'Clarendon' + ' Parkway', 'Kalamazoo', 'TX', '42432')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dabfeed', '2020', 'South' + ' Pass', 'Hartford', 'UT', '43108')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kwilith', '2054', 'Westridge' + ' Place', 'Albuquerque', 'VT', '34507')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yakidoo', '2064', 'David' + ' Plaza', 'Green Bay', 'VA', '32902')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Edgeify', '2082', 'Gina' + ' Point', 'Minneapolis', 'WA', '90311')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Meevee', '2108', 'Blue Bill Park' + ' Road', 'Tampa', 'WV', '12404')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Muxo', '2119', 'East' + ' Street', 'Bryan', 'WI', '97364')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Eare', '2120', 'Judy' + ' Terrace', 'Boston', 'WY', '75994')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skinder', '2184', 'Crownhardt' + ' Trail', 'Minneapolis', 'AL', '42140')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yambee', '2228', 'Doe Crossing' + ' Way', 'Washington', 'AK', '29569')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Feedmix', '2232', 'Melvin' + ' Alley', 'Houston', 'AZ', '23617')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Feednation', '2234', 'Fuller' + ' Avenue', 'San Francisco', 'AR', '65729')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Edgeclub', '2243', 'Packers' + ' Center', 'Racine', 'CA', '81032')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Twimbo', '2250', 'Superior' + ' Circle', 'Fort Smith', 'CO', '34595')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tagfeed', '2268', 'Hudson' + ' Court', 'Oklahoma City', 'CT', '50111')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Trilia', '2368', 'Ryan' + ' Crossing', 'Sioux Falls', 'DE', '19614')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Ozu', '2384', 'Buell' + ' Drive', 'San Antonio', 'FL', '26133')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Twitterbeat', '2425', 'Sachtjen' + ' Hill', 'Cincinnati', 'GA', '29292')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Katz', '2463', 'Express' + ' Junction', 'Lexington', 'HI', '39136')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Realpoint', '2488', 'Del Mar' + ' Lane', 'Atlanta', 'ID', '38792')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Trilith', '2574', 'Del Sol' + ' Park', 'Minneapolis', 'IL', '71875')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Gigashots', '2606', 'Vermont' + ' Parkway', 'Orlando', 'IN', '48578')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Rhycero', '2619', 'Hanson' + ' Pass', 'Jamaica', 'IA', '88960')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Pixonyx', '2647', 'Eggendart' + ' Place', 'Raleigh', 'KS', '74902')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skyble', '2661', 'Merrick' + ' Plaza', 'El Paso', 'KY', '56673')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zoozzy', '2758', 'Derek' + ' Point', 'Albuquerque', 'LA', '70731')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Browsebug', '2766', 'Warner' + ' Road', 'Brooklyn', 'ME', '88798')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Abatz', '2780', 'Petterle' + ' Street', 'Arlington', 'MD', '54585')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Voolith', '2802', 'Swallow' + ' Terrace', 'Kansas City', 'MA', '10607')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Riffpedia', '2832', 'Stoughton' + ' Trail', 'Albany', 'MI', '43457')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skippad', '2838', 'Becker' + ' Way', 'Kansas City', 'MN', '54523')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kare', '2874', 'Hauk' + ' Alley', 'Wilmington', 'MS', '76406')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yombu', '2897', 'Village' + ' Avenue', 'San Diego', 'MO', '97515')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tagtune', '3064', 'Moland' + ' Center', 'Denver', 'MT', '77003')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Avamm', '3094', 'Hintze' + ' Circle', 'Norwalk', 'NE', '55972')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jatri', '3100', 'Tony' + ' Court', 'Spring Hill', 'NV', '46734')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Flipopia', '3120', 'Daystar' + ' Crossing', 'Decatur', 'NH', '83925')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Eazzy', '3260', 'Lien' + ' Drive', 'Phoenix', 'NJ', '98438')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Vinder', '3308', 'Riverside' + ' Hill', 'Oakland', 'NM', '58255')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Photofeed', '3328', 'Rieder' + ' Junction', 'Saint Petersburg', 'NY', '35682')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Quinu', '3374', 'Duke' + ' Lane', 'Dallas', 'NC', '40356')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Devbug', '3440', 'High Crossing' + ' Park', 'Mobile', 'ND', '66198')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Bluejam', '3444', 'Hovde' + ' Parkway', 'Fresno', 'OH', '16958')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Twinte', '3514', 'Utah' + ' Pass', 'Philadelphia', 'OK', '32897')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Blogspan', '3527', 'Annamark' + ' Place', 'Chicago', 'OR', '96461')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Twiyo', '3543', 'Fisk' + ' Plaza', 'Baltimore', 'PA', '41764')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kazio', '3548', 'Barby' + ' Point', 'Young America', 'RI', '52485')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Quimm', '3803', 'Prentice' + ' Road', 'Schaumburg', 'SC', '48033')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Photobean', '3861', 'Buena Vista' + ' Street', 'Washington', 'SD', '83150')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Shuffletag', '3915', 'Meadow Valley' + ' Terrace', 'Newark', 'TN', '71411')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tazzy', '3919', 'Loeprich' + ' Trail', 'Denver', 'TX', '76639')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Nlounge', '3976', 'Forest Run' + ' Way', 'South Bend', 'UT', '64678')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Reallinks', '4008', 'Melrose' + ' Alley', 'Las Vegas', 'VT', '85174')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Devshare', '4046', 'Goodland' + ' Avenue', 'Miami', 'VA', '81592')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Mydo', '4063', 'Sommers' + ' Center', 'Atlanta', 'WA', '92140')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Devpulse', '4072', 'Bunker Hill' + ' Circle', 'Mesquite', 'WV', '69989')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Brainsphere', '4073', 'Arrowood' + ' Court', 'Saint Augustine', 'WI', '93956')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Twitterlist', '4136', 'Brickson Park' + ' Crossing', 'Largo', 'WY', '27532')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jabbersphere', '4157', 'Monument' + ' Drive', 'Evansville', 'AL', '53081')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Oyoyo', '4177', 'Continental' + ' Hill', 'El Paso', 'AK', '26934')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Buzzster', '4197', 'Carpenter' + ' Junction', 'Orlando', 'AZ', '99071')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zoonoodle', '4210', 'Tomscot' + ' Lane', 'Brooklyn', 'AR', '40751')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Mudo', '4218', 'Elka' + ' Park', 'Washington', 'CA', '59253')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Thoughtblab', '4230', 'Grayhawk' + ' Parkway', 'Dallas', 'CO', '12854')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tagchat', '4243', 'Dakota' + ' Pass', 'Cedar Rapids', 'CT', '84452')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Geba', '4253', 'Grover' + ' Place', 'Moreno Valley', 'DE', '52360')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Gigabox', '4331', 'Westport' + ' Plaza', 'Austin', 'FL', '52796')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Thoughtworks', '4408', 'North' + ' Point', 'Ann Arbor', 'GA', '36896')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Voolia', '4414', 'Bluestem' + ' Road', 'Spokane', 'HI', '69003')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Brightdog', '4425', 'Armistice' + ' Street', 'Minneapolis', 'ID', '41442')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Brainlounge', '4442', 'Bay' + ' Terrace', 'Fort Lauderdale', 'IL', '13797')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Meejo', '4463', 'Trailsway' + ' Trail', 'Harrisburg', 'IN', '57726')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Quamba', '4475', 'Birchwood' + ' Way', 'Savannah', 'IA', '41632')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Voonder', '4490', 'Grasskamp' + ' Alley', 'Bronx', 'KS', '55682')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yozio', '4565', 'Dexter' + ' Avenue', 'San Francisco', 'KY', '93962')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Brightbean', '4600', 'Lawn' + ' Center', 'Des Moines', 'LA', '64666')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Buzzdog', '4628', 'Dahle' + ' Circle', 'Springfield', 'ME', '45966')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yata', '4637', 'Pankratz' + ' Court', 'El Paso', 'MD', '45446')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kamba', '4647', 'Nelson' + ' Crossing', 'Worcester', 'MA', '98989')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Abata', '4721', 'Mockingbird' + ' Drive', 'Roanoke', 'MI', '52468')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Divape', '4759', 'Carberry' + ' Hill', 'Orange', 'MN', '44106')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('BlogXS', '4779', 'Waywood' + ' Junction', 'Denver', 'MS', '82694')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Topdrive', '4795', 'Oak Valley' + ' Lane', 'Stockton', 'MO', '57201')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Yabox', '4796', 'Eastlawn' + ' Park', 'Saint Paul', 'MT', '53512')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Shuffledrive', '4840', 'Fairview' + ' Parkway', 'Minneapolis', 'NE', '56955')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Eamia', '4869', 'Gateway' + ' Pass', 'New York City', 'NV', '47535')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Brainverse', '4914', 'Maple' + ' Place', 'South Bend', 'NH', '91902')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jabbertype', '4997', 'Charing Cross' + ' Plaza', 'Olympia', 'NJ', '35844')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jazzy', '5051', 'Old Shore' + ' Point', 'Detroit', 'NM', '92967')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Eire', '5076', 'Elgar' + ' Road', 'El Paso', 'NY', '60305')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kayveo', '5096', 'Main' + ' Street', 'Aurora', 'NC', '82464')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Zoomzone', '5140', 'Luster' + ' Terrace', 'Norfolk', 'ND', '53916')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Dabvine', '5181', 'Dunning' + ' Trail', 'Salem', 'OH', '50324')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Skibox', '5275', 'Bobwhite' + ' Way', 'Washington', 'OK', '51915')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Camido', '5404', 'Hagan' + ' Alley', 'Garden Grove', 'OR', '97859')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Jabberbean', '5435', 'Garrison' + ' Avenue', 'Washington', 'PA', '78026')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Viva', '5598', 'Boyd' + ' Center', 'Charleston', 'RI', '49901')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Youopia', '5633', 'Esch' + ' Circle', 'Kansas City', 'SC', '94827')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Latz', '5717', 'Northport' + ' Court', 'Jamaica', 'SD', '57072')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Centizu', '5800', 'Bunting' + ' Crossing', 'Houston', 'TN', '92698')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Divanoodle', '5812', 'Redwing' + ' Drive', 'New York City', 'TX', '53064')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Realblab', '5831', 'Eliot' + ' Hill', 'Gainesville', 'UT', '58496')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Pixoboo', '5860', 'Sundown' + ' Junction', 'El Paso', 'VT', '66898')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Riffpath', '5923', 'Kings' + ' Lane', 'Irvine', 'VA', '98779')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Mymm', '5934', 'Corben' + ' Park', 'Austin', 'WA', '37817')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Kwideo', '5937', 'Brentwood' + ' Parkway', 'Washington', 'WV', '34723')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Camimbo', '5948', 'Sachs' + ' Pass', 'Long Beach', 'WI', '47587')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Fivechat', '6009', 'Portage' + ' Place', 'Pompano Beach', 'WY', '39725')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Tagcat', '6043', 'Rusk' + ' Plaza', 'Kansas City', 'AL', '23671')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Demivee', '6057', 'Dorton' + ' Point', 'Tucson', 'AK', '53787')
insert into addresses (Name, StreetNumber, StreetName, City, State, ZipCode) values ('Eimbee', '6133', 'Manufacturers' + ' Road', 'Tucson', 'AZ', '49624')
go
--Associate 1 random address to every user
while exists (select 1 from Users u where not exists (select 1 from UserAddress where Users_Id=u.id))
	insert into UserAddress 
		select top 1 u.id as Users_Id, a.id as Addresses_Id
			from users u, addresses a
			where not exists (select 1 from UserAddress where Users_Id=u.id)
				and not exists (select 1 from UserAddress where Addresses_Id=a.id)
go
--Associate 1 random user to every address (means some users will have 2 addresses (a good thing)
while exists (select 1 from Addresses a where not exists (select 1 from UserAddress where Addresses_Id=a.id))
	insert into UserAddress 
		select top 1 u.id as Users_Id, a.id as Addresses_Id
			from users u, addresses a
			where not exists (select 1 from UserAddress where Addresses_Id=a.id)
				and (select count(1) from UserAddress where Users_Id=u.id) = 1
go
--Currently works, but the while does not know when to end
while exists (select 1
				 from users u, addresses a
				 where
					--Address id is even
					a.id % 2 = 0
					--Address only linked to a single user so far
					and (select count(1) from UserAddress where Addresses_Id=a.id) = 1
					--User only linked to a single address so far
					and (select count(1) from UserAddress where Users_Id=u.id) = 1
					--Row can not already exist
					and not exists (select 1 from UserAddress where Users_Id=u.id and Addresses_Id=a.id)
				)
	insert into UserAddress
		select top 1 u.id as Users_Id, a.id as Addresses_Id
			from users u, addresses a
			where
				a.id % 2 = 0
				and (select count(1) from UserAddress where Addresses_Id=a.id) = 1
				and (select count(1) from UserAddress where Users_Id=u.id) = 1
				and not exists (select 1 from UserAddress where Users_Id=u.id and Addresses_Id=a.id)
go